### ISSUE TITLE
when checkAll, the checkboxs are not selected

### ISSUE THREAD

**Issue by summer-liu** [vitalets/checklist-model#49]
When I click uncheckAll button, $scope.selectedItems is empty, but all the checkboxs are still selected. Is this because the id is not Number? 
my data is like this:

    $scope.data = [{
    id: "234dfsdw43",
    name: "name1"
    },
    {
    id: "e4w54gr4",
    name: "name2"
    }]

JS:

    $scope.checkAll = function() {
     $scope.selectedItems = $scope.data.map(function(item) { return item.id; });
    };

    $scope.uncheckAll = function() {
                $scope.selectedItems = [];
            };

HTML:

    <div ng-repeat="item in data">
    <input type="checkbox" checklist-model="selectedItems" checklist-value="item.id"> {{ item.name}}
     </div>
    <button ng-click="checkAll()">check all</button>
    <button ng-click="uncheckAll()">uncheck all</button>

**Comment by kJamesy** [comment]
Same issue too. I've had to find a workaround

**Comment by kadikraman** [comment]
Same issue. I fixed mine by replacing

<pre><code> $scope.selection = angular.copy($scope.divisions); </pre> </code>
with
<br/>
<pre><code> angular.copy($scope.divisions, $scope.selection); </pre> </code>

(Similarily with the **uncheck()** function, I had to replace it with **angular.copy([ ], selection)**)

How I came to this: I put a breakpoint in line 73 of **checklist-model.js** - this is meant to watch the original model change:

<pre><code>
    // watch original model change
    scope.$parent.$watch(attrs.checklistModel, function(newArr, oldArr) {
      scope.checked = contains(newArr, value);
    }, true);
</pre></code>

And this event never fired when I used **bar = angular.copy(foo)**. Apparently angular was still [watching the old reference](http://stackoverflow.com/questions/17064637/why-does-angular-not-databind-data-when-an-object-is-copied-from-another-object) to my array, but using **angular.copy(foo, bar)** copies the values properly.

**Comment by hroussel** [comment]
+1

**Comment by mamantoha** [comment]
@kadikraman thank you very match :wink:

**Comment by samjulien** [comment]
@kadikraman really well done, thank you so much. @vitalets you might want to update your code to reflect this correction, or let @kadikraman pull and add it.

**Comment by swxy** [comment]
+1

**Comment by harpster604** [comment]
+1

**Comment by yashikagarg13** [comment]
+1 Thank you so much.

**Comment by beradrian** [comment]
@kadikraman do you have a pull request for it? Also a test example to be added to the examples will be good.

**Comment by beradrian** [comment]
I fixed the tests.

**Comment by FrancoisMartin** [comment]
+1 @kadikraman code works well.
But the documentation is still wrong.

**Comment by beradrian** [comment]
@FrancoisMartin, what exactly is wrong in the documentation so I can fix it?

**Comment by FrancoisMartin** [comment]
![screen shot 2015-11-18 at 11 28 36-1](https://cloud.githubusercontent.com/assets/2278002/11240253/7947748c-8df1-11e5-88a6-6964b8069993.png)
Check All / Uncheck All only works with ```angular.copy($scope.allMyList, $scope.selectedList)```

I'm using Angular 1.4.7

**Comment by beradrian** [comment]
Does the demo not work for you? The code that you see is the code used in the demo and for me it works.

**Comment by FrancoisMartin** [comment]
It doesn't work with Angular 1.4.7, the demo is using an older version of angular.

**Comment by beradrian** [comment]
I updated to Angular 1.4.8. @FrancoisMartin, does it work for you?

**Comment by FrancoisMartin** [comment]
Yes, it works fine.
My problem might be something related to my project only, so i guess we can forget this issue :)
